### ISSUE TITLE
Store of an Event sometims fails with OTransactionException

### ISSUE THREAD

**Issue by veny** [veny/smevente#42]

**Comment by veny** [comment]
log sample:
com.orientechnologies.orient.core.exception.OTransactionException: Error on transaction commit
        at com.orientechnologies.orient.client.remote.OStorageRemote.commitEntry(OStorageRemote.java:2000)
        at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1106)
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.commit(OStorageRemoteThread.java:445)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:470)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2406)
        at com.orientechnologies.orient.object.db.OObjectDatabaseTx.commit(OObjectDatabaseTx.java:551)
        at com.orientechnologies.orient.object.db.OObjectDatabaseTx.commit(OObjectDatabaseTx.java:546)
        at veny.smevente.dao.orientdb.DatabaseWrapper.execute(DatabaseWrapper.java:151)
        at veny.smevente.dao.orientdb.AbstractDaoOrientdb.persist(AbstractDaoOrientdb.java:209)
        at veny.smevente.service.impl.EventServiceImpl.storeEvent(EventServiceImpl.java:122)
        at veny.smevente.server.UserController.storeEvent(UserController.java:187)
        at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)


and

Caused by: com.orientechnologies.orient.core.exception.OValidationException: The field 'Procedure.unit' cannot be null, record: Procedure#16
:10{unit:null,revision:0,name:Air flow,color:f7a5e1,time:45,messageText:Dobry den,pripominame Vam termin osetreni dne #{date} v #{time}.V pr
ipade zmeny volejte.Dekujeme.S pozdravem #{doctor},type:IN_CALENDAR} v1
        at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:253)
        at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:1915)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2228)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1703)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1694)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:75)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSeria
lizerBinaryV0.java:674)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSeri
alizerBinaryV0.java:688)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerial
izerBinaryV0.java:572)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBin
aryV0.java:261)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary
.java:104)
